services:
  servico-notificacoes:
    build: .
    container_name: healthsys-servico-notificacoes
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      RABBIT_HOST: healthsys-rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASS: guest
      DB_HOST: healthsys-postgres-notificacoes
    depends_on:
      postgres-notificacoes:
        condition: service_healthy
    networks:
      - healthsys-network

  postgres-notificacoes:
    image: postgres:16-alpine
    container_name: healthsys-postgres-notificacoes
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: notificacoes_db
      POSTGRES_USER: healthsys
      POSTGRES_PASSWORD: healthsys
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthsys -d notificacoes_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - healthsys-network

networks:
  healthsys-network:
    external: true